### ISSUE TITLE
`easystats` meta-package CRAN release

### ISSUE THREAD

**Issue by IndrajeetPatil** [easystats/easystats#113]
Now that `report` is on `CRAN`, maybe we can finally submit the meta-package to `CRAN`?

It will make the life of our users easier, since a lot of people seem to be running into GitHub API issues.

- [x] add `cran_comments.md` to explain why a meta-package like this is needed
- [x] add a function to install suggested packages (#135)
- [x] complete #143
- [x] DESCRIPTION, add authors/contributors
- [x] DESCRIPTION, change title
- [x] DESCRIPTION, update package description (add and emphasize vignettes/tutorials, useful for teaching, ...)
- [x] get `datawizard` on CRAN
- [ ] add vignettes
  - [x] #103
  - [ ] #104
  - [ ] #108 
  - [x] https://github.com/easystats/easystats/issues/137
  - [ ] https://github.com/easystats/easystats/issues/73

**Comment by strengejacke** [comment]
I'm not sure how chances are, but I bet rather low. I tried this once with my "strengejacke" package, and the answer was that CRAN prefers not to publish packages whose only purpose is to load other packages. Not sure how tidyverse made it on CRAN, though.

**Comment by DominiqueMakowski** [comment]
We could try, instead of loading all the other packages, we just import them and re-export all of their functions 😁

**Comment by IndrajeetPatil** [comment]
I think we should use `tidyverse` package as the precedent for our meta-package and refer to it in our correspondence with the `CRAN` team if it gets rejected. 

That said, `CRAN` policies change frequently and so even if the package was rejected in the past is not predictive of whether it will be now.

**Comment by strengejacke** [comment]
What I had in mind, and what could potentially increase the use of the package beyond "just loading", would indeed be having vignettes like #103, #104 or #108. It's not uncommon to have packages as "supplemental material" for teaching. If we can convince the team that the benefit of the _easystats_ package would be an easier access to R for new users, that might be a benefit.

**Comment by bwiernik** [comment]
I agree that the "easy access for new users" is a good attack angle

**Comment by strengejacke** [comment]
(revised my last sentence, was a bit confusing)

**Comment by IndrajeetPatil** [comment]
To be worked on after https://github.com/easystats/easystats/issues/256 is closed.

**Comment by IndrajeetPatil** [comment]
Have we decided who is going to be the maintainer for this one? 

@strengejacke If you want to maintain this one, I will be happy to take over maintainership of `{see}` to balance out the maintenance load.

**Comment by strengejacke** [comment]
Ok, sounds good to me.

**Comment by strengejacke** [comment]
Currently @DominiqueMakowski is maintainer, Dom, if you prefer, you can maintain this package. But I'm happy to maintain this package, too, if you want.

**Comment by DominiqueMakowski** [comment]
https://win-builder.r-project.org/WWFnPOOoUPVY

> But I'm happy to maintain this packag

Yeah you can go ahead ;)

**Comment by IndrajeetPatil** [comment]
Congrats, @easystats/core-team! 🥳
https://cran.r-project.org/web/packages/easystats/index.html

**Comment by strengejacke** [comment]
Someone MUST tweet about it...

**Comment by IndrajeetPatil** [comment]
Already done! 😉

**Comment by strengejacke** [comment]
Yes, I just saw it :-)
